name: medallionOfFlight
version: '1.0.0'
main: me.jellie06.medallionofflight.MedallionOfFlight
api-version: '1.21'
author: Jellie06
description: A craftable medallion that grants survival players flight
